# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sinaRank',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('rankNum', models.IntegerField()),
                ('time', models.DateField(verbose_name='date published')),
            ],
        ),
    ]
