# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_sinarank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinarank',
            name='id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sinarank',
            name='rankNum',
            field=models.CharField(max_length=128),
        ),
    ]
