# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20171128_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinarank',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
