# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20171128_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinarank',
            name='rankNum',
            field=models.IntegerField(),
        ),
    ]
