# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20171128_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='biliBileDetail',
            fields=[
                ('pkid', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('fkid', models.CharField(max_length=128)),
                ('square_cover', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('pub_time', models.CharField(max_length=255)),
                ('pub_index', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='biliBiliDate',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=255)),
                ('date_ts', models.DateTimeField()),
                ('day_of_week', models.IntegerField()),
                ('is_today', models.IntegerField()),
            ],
        ),
    ]
